#!/usr/bin/env node
// Copyright (c) 2026 MIMO. MIT License.
// https://github.com/Nemophilistc/ai-data-analyzer-mcp

import { readFileSync, writeFileSync, existsSync } from 'fs';
import { join } from 'path';
import { createInterface } from 'readline';
import { startWebServer } from './web-server.js';
import { exec } from 'child_process';

const ENV_PATH = join(process.cwd(), '.env');

interface EnvConfig {
  provider: string;
  apiKey: string;
  baseUrl: string;
  model: string;
}

function parseEnv(): EnvConfig | null {
  if (!existsSync(ENV_PATH)) return null;

  const content = readFileSync(ENV_PATH, 'utf-8');
  const vars: Record<string, string> = {};
  for (const line of content.split('\n')) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const idx = trimmed.indexOf('=');
    if (idx === -1) continue;
    vars[trimmed.slice(0, idx).trim()] = trimmed.slice(idx + 1).trim();
  }

  const provider = vars.AI_PROVIDER;
  if (!provider) return null;

  return {
    provider,
    apiKey: vars.AI_API_KEY || '',
    baseUrl: vars.AI_BASE_URL || '',
    model: vars.AI_MODEL || '',
  };
}

function writeEnv(config: EnvConfig): void {
  const lines = [
    '# AI Data Analyzer Configuration',
    '# Generated by npx ai-data-analyzer',
    '',
    `AI_PROVIDER=${config.provider}`,
    `AI_API_KEY=${config.apiKey}`,
    `AI_BASE_URL=${config.baseUrl}`,
    `AI_MODEL=${config.model}`,
    '',
  ];
  writeFileSync(ENV_PATH, lines.join('\n'), 'utf-8');
}

function ask(rl: ReturnType<typeof createInterface>, question: string): Promise<string> {
  return new Promise((resolve) => rl.question(question, resolve));
}

async function setupWizard(): Promise<EnvConfig> {
  const rl = createInterface({ input: process.stdin, output: process.stdout });

  console.log();
  console.log('  \x1b[36m=== AI Data Analyzer - First Time Setup ===\x1b[0m');
  console.log();

  console.log('  Select AI provider:');
  console.log('    1) OpenAI     (GPT-4o, needs API key)');
  console.log('    2) DeepSeek   (DeepSeek-V3, needs API key)');
  console.log('    3) Ollama     (local models, free)');
  console.log();

  const choice = await ask(rl, '  Enter number (1-3): ');
  let config: EnvConfig;

  switch (choice.trim()) {
    case '1': {
      const key = await ask(rl, '  Enter OpenAI API Key: ');
      config = {
        provider: 'openai',
        apiKey: key.trim(),
        baseUrl: 'https://api.openai.com/v1',
        model: 'gpt-4o',
      };
      break;
    }
    case '2': {
      const key = await ask(rl, '  Enter DeepSeek API Key: ');
      config = {
        provider: 'deepseek',
        apiKey: key.trim(),
        baseUrl: 'https://api.deepseek.com/v1',
        model: 'deepseek-chat',
      };
      break;
    }
    case '3': {
      const url = await ask(rl, '  Ollama base URL (default: http://localhost:11434): ');
      const model = await ask(rl, '  Model name (default: qwen2.5:7b): ');
      config = {
        provider: 'ollama',
        apiKey: 'ollama',
        baseUrl: url.trim() || 'http://localhost:11434/v1',
        model: model.trim() || 'qwen2.5:7b',
      };
      break;
    }
    default:
      rl.close();
      console.log('  \x1b[31mInvalid choice. Please run again.\x1b[0m');
      process.exit(1);
  }

  rl.close();

  writeEnv(config);
  console.log();
  console.log('  \x1b[32m✓ Configuration saved to .env\x1b[0m');
  console.log();

  return config;
}

function openBrowser(url: string): void {
  const cmd = process.platform === 'win32' ? 'start' : process.platform === 'darwin' ? 'open' : 'xdg-open';
  exec(`${cmd} "${url}"`, (err) => {
    if (err) {
      console.log(`  Could not auto-open browser. Please visit: ${url}`);
    }
  });
}

async function main() {
  console.log();
  console.log('  \x1b[1m\x1b[36m🔍 AI Data Analyzer\x1b[0m');
  console.log('  \x1b[90mAI-powered database analysis tool\x1b[0m');
  console.log();

  let config = parseEnv();

  if (!config) {
    config = await setupWizard();
  } else {
    console.log(`  Using AI provider: \x1b[32m${config.provider}\x1b[0m`);
  }

  const port = Number(process.env.PORT || '3456');
  await startWebServer(config, port);
  const url = `http://localhost:${port}`;

  console.log();
  console.log(`  \x1b[32m✓ Server running at ${url}\x1b[0m`);
  console.log();
  console.log('  \x1b[90mPress Ctrl+C to stop\x1b[0m');
  console.log();

  openBrowser(url);
}

main().catch((err) => {
  console.error('\x1b[31mFatal error:\x1b[0m', err.message);
  process.exit(1);
});
